### ISSUE TITLE
Two issues with you nice component

### ISSUE THREAD

**Issue by johnkwaters** [tschinz/dokuwiki_skype_plugin#1]
It cant deal with Microsoft organizational accounts (windows live).
Also, the Skype button always show the prompt to download skype

**Comment by tschinz** [comment]
Hello Johnkwaters,

The second problem is purely related to the Javascript from skype. There is nothing I can do about it. The popup with the two buttons "Download Skype" + "Already have Skype" is inevitable.

For the first problem, I don't have a Microsoft account, but I'll look into the problem these coming days.

Cheer tschinz

**Comment by tschinz** [comment]
Hi there,
I made an update to use the latest version of the skype button. I dont' have a microsoft account (I'll keep my skype account as long as possible)

@johnkwaters  can you test it, and close the issue afterwards if it's resolved for you.

There are less functionalities only call and chat or both are possible. But therefore no stupid popup anymore ;-). 

Cheers
