### ISSUE TITLE
Does not show any Button

### ISSUE THREAD

**Issue by ravage84** [tschinz/dokuwiki_skype_plugin#4]
DokuWiki release 2018-04-22b "Greebo"

After installation through admin backend (not manually), I used the syntax from the doku page.
I could see that it injected some HTML (a DIV) and some JS code but it didn't show any button.

**Comment by tschinz** [comment]
Hello,
my dokuwiki also uses Release 2018-04-22a "Greebo". Is works. To you have Skype installed in you computer.
Can you see the button here: [http://relia.zapto.org/zawiki/doku.php/tschinz:dw_skype](http://relia.zapto.org/zawiki/doku.php/tschinz:dw_skype)?

See my screenshot:
![image](https://user-images.githubusercontent.com/1192968/74738149-99401400-5256-11ea-9d03-7b278f1fc4d9.png)

I don't really support this plugin anymore normally. But apparently it still work in my case.

Let me know
